apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass123"
  MYSQL_DATABASE: "intermediate_db"
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "apppass123"