apiVersion: apps/v1
kind: Deployment
metadata:
  name: intermediate-project
  labels:
    app: intermediate-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intermediate-project
  template:
    metadata:
      labels:
        app: intermediate-project
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: intermediate-project
          image: yisraelackerman/intermediate-project:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v2.0.0"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
