apiVersion: v1
kind: Service
metadata:
  name: intermediate-project
spec:
  selector:
    app: intermediate-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
