apiVersion: v1
kind: Service
metadata:
  name: intermediate-project
spec:
  selector:
    app: intermediate-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

# שורה ראשונה v1 זה גירסת הAPI
# משב מסוג Service יושב מחוץ לפוד יכול לשמש כלודבלאנסר בתוך הקלסטר
# ports פרוטקול TCP, מקשיב ב80 מפנה 5000 
# type ClusterIP - שירות הפשרה לתקשורת בתוך הקלסטר בלבד